version: "3.5"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.1/24"
services:
  mysql:
    image: mysql
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.28.0.3
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ChoosePlans
      MYSQL_ROOT_PASSWORD: e1ZyC7k1lN0Z
  choose-plan-service:
    image: choose-plan-backend-service:master
    environment:
      NODE_ENV: production
    networks:
      app_net:
        ipv4_address: 172.28.0.4
    ports:
      - 9000:9000


